sudo: required
services:
  - docker

before_install:
  - docker build -t moon2k/complex-app -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true moon2k/complex-app/client npm run test

after_success:
  - docker build -t moon2k/complex-client -f ./client
  - docker build -t moon2k/complex-nginx -f ./nginx
  - docker build -t moon2k/complex-server -f ./server
  - docker build -t moon2k/complex-worker -f ./worker
  # Login Docker CLI
  # --password-stdin opens input for password and echo presets it
  - echo "$DOCKERHUB_PASSWORD" | docker login -u $DOCKERHUB_LOGIN --password-stdin
  - docker push moon2k/complex-client
  - docker push moon2k/complex-nginx
  - docker push moon2k/complex-server
  - docker push moon2k/complex-worker
